spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: 123456
    hikari:
      minimum-idle: 2
      maximum-pool-size: 9
  banner:
    location: classpath:banner.txt
  responseJsonFactory: org.example.resp.RespFactory
server:
  port: 8888
  compression:
    enabled: true
    mime-types:
      - text/*
      - application/javascript
      - application/json
      - application/xml
    min-response-size: 64B